// DO NOT EDIT. Generated by 'gorums' plugin for protoc-gen-go
// Source file to edit is: qspec_tmpl

package dev

// QuorumSpec is the interface that wraps every quorum function.
type QuorumSpec interface {
	// ReadQF is the quorum function for the Read
	// quorum call method.
	ReadQF(req *ReadRequest, replies []*State) (*State, bool)

	// ReadCorrectableQF is the quorum function for the ReadCorrectable
	// correctable quorum call method.
	ReadCorrectableQF(req *ReadRequest, replies []*State) (*State, int, bool)

	// ReadCustomReturnQF is the quorum function for the ReadCustomReturn
	// quorum call method.
	ReadCustomReturnQF(req *ReadRequest, replies []*State) (*MyState, bool)

	// ReadFutureQF is the quorum function for the ReadFuture
	// asynchronous quorum call method.
	ReadFutureQF(req *ReadRequest, replies []*State) (*State, bool)

	// ReadPrelimQF is the quorum function for the ReadPrelim
	// correctable prelim quourm call method.
	ReadPrelimQF(req *ReadRequest, replies []*State) (*State, int, bool)

	// WriteQF is the quorum function for the Write
	// quorum call method.
	WriteQF(req *State, replies []*WriteResponse) (*WriteResponse, bool)

	// WriteFutureQF is the quorum function for the WriteFuture
	// asynchronous quorum call method.
	WriteFutureQF(req *State, replies []*WriteResponse) (*WriteResponse, bool)

	// WritePerNodeQF is the quorum function for the WritePerNode
	// quorum call method.
	WritePerNodeQF(req *State, replies []*WriteResponse) (*WriteResponse, bool)
}
